service: sync-vs-async

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1

functions:
  sync:
    handler: handler.f_sync
    events:
      - http:
          path: sync
          method: get
          async: false

  async:
    handler: handler.f_async
    events:
      - http:
          path: async
          method: get
          async: true

