service: sync-vs-async

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  endpointType: REGIONAL

functions:
  sync:
    handler: handler.func
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: sync
          method: get
          async: false

  async:
    handler: handler.func
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: async
          method: get
          async: true

